import enum

TOTAL_CURRENT_LIABILITY = "total_current_liability"
TOTAL_CURRENT_ASSET = "total_current_asset"
TOTAL_NON_CURRENT_ASSET = "total_non_current_asset"
TOTAL_SHAREHOLDERS_FUNDS = "total_shareholders_funds"
TOTAL_ASSET = "total_asset"
LONG_TERM_BORROWING = "long_term_borrowing"
SHORT_TERM_BORROWINGS = "short_term_borrowings"
CASH_FLOWS = "cash_flows"
CASH_FLOW_FROM_OPERATING_ACTIVITIES = "cash_flow_from_operating_activities"
CURRENT_RATIO = "current_ratio"
GROSS_MARGIN = "gross_margin"
ASSET_TURNOVER_RATIO = "asset_turnover_ratio"
RETURN_ON_ASSETS = "return_on_assets"
RETURN_ON_EQUITIES = "return_on_equities"
RETURN_ON_ASSET = "return_on_asset"
INCOMES = "incomes"
INCOME = "income"
NET_SALE = "net_sale"
TOTAL_EXPENSE = "total_expense"
ISSUED_SHARES = "issued_shares"
FINANCIAL_YEAR = "financial_year"

INDUSTRY_PE = "industry_pe"
PE = "pe"
MARKET_CAPITAL_FULL = "market_capital_full"
ISINID = "isinid"
MONEYCONTROL_SCID = "moneycontrol_scid"
NAME = "name"
PUT_TO_CALL = "put_to_call"
EPS_TWELVE_MONTH = "eps_twelve_month"
GROUP = "group"
FACE_VALUE = "face_value"
DIVIDEND_PERCENTAGE = "dividend_percentage"
BOOK_VALUE = "book_value"
CASH_EPS = "cash_eps"
PRICE = "price"
INDUSTRY = "industry"
SUB_INDUSTRY = "sub_industry"
HISTORICAL_PRICES = "historical_prices"
TAGS = "tags"
SECTOR = "sector"
ACTIVE = "active"
BALANCE_SHEET = "balance_sheet"
PROFIT_LOSS_STATEMENT = "income_statements"
FINANCIAL_RATIOS = "financial_ratios"
LAST_DATE_UPDATED = "last_date_updated"
DATE_CREATED = "date_created"

NEGLIGIBLE_VALUE_TO_AVOID_DIVIDE_BY_ZERO_VALUE = 0.01

GROSS_PURCHASE_KEY = "gross_purchase"
GROSS_SALE_KEY = "gross_sale"
DATE_KEY = "date"


@enum.unique
class InstitutionalInvestor(enum.Enum):
    FII = "FII"
    DII = "DII"
